spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888

application:
  config:
    imports-url:
      host: http://localhost:8222/import
    common_service-url:
      host: http://localhost:8008
      random-UUID: /common-utils/random-UUID


secret: monopoco123
superToken: hungdzqua
accessTokenExp: 86400000 # 24h
