spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring:
#          json:
#            type:
#              mapping: historyeven:com.monopoco.purchaseorder.client.dto.HistoryDTO
    topic:
      name: history


secret: monopoco123
superToken: hungdzqua
accessTokenExp: 86400000 # 24h
