spring:
  application:
    name: inventory-service
  config:
    import: optional:configserver:http://localhost:8888


secret: monopoco123
superToken: hungdzqua
accessTokenExp: 86400000 # 24h
authURL: http://localhost:8222/auth
warehouseURL: http://localhost:8222/warehouses
historyURL: http://localhost:8222/histories
