spring:
  application:
    name: supplier-service
  config:
    import: optional:configserver:http://localhost:8888


secret: monopoco123
superToken: hungdzqua
accessTokenExp: 86400000 # 24h
productURL: http://localhost:8222/products
