
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: import-service
          uri: http://localhost:8070
          predicates:
            - Path=/import/**
        - id: product-service
          uri: http://localhost:8090
          predicates:
            - Path=/products/**
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8222
