spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowedOriginPatterns: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: import-service
          uri: http://localhost:8070
          predicates:
            - Path=/import/**
        - id: product-service
          uri: http://localhost:8090
          predicates:
            - Path=/products/**
        - id: auth-service
          uri: http://localhost:8040
          predicates:
            - Path=/auth/**
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8222
