spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowedOriginPatterns: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: inventory-service
          uri: http://localhost:8030
          predicates:
            - Path=/inventories/**
        - id: product-service
          uri: http://localhost:8090
          predicates:
            - Path=/products/**
        - id: auth-service
          uri: http://localhost:8040
          predicates:
            - Path=/auth/**
        - id: warehouse-service
          uri: http://localhost:8020
          predicates:
            - Path=/warehouses/**
        - id: history-service
          uri: http://localhost:8010
          predicates:
            - Path=/histories/**
        - id: supplier-service
          uri: http://localhost:8060
          predicates:
            - Path=/suppliers/**
        - id: purchase-order-service
          uri: http://localhost:8050
          predicates:
            - Path=/purchase_orders/**
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8222
