spring:
  data:
    mongodb:
      host: localhost
      port: 2717
      database: WMS_History
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8010
